### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addError' of undefined

### ISSUE THREAD

**Issue by RB786** [huangjinlin/atom-markdown-to-html#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Ubuntu 18.04.1
**Thrown From**: [markdown-to-html](https://github.com/huangjinlin/atom-markdown-to-html) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'addError' of undefined

```
At /home/rbharti/.atom/packages/markdown-to-html/lib/utils.js:35

TypeError: Cannot read property 'addError' of undefined
    at /packages/markdown-to-html/lib/utils.js:35:34
    at fs.js:1283:7
    at FSReqWrap.oncomplete (fs.js:135:15)
```

### Commands

```
     -1:09.7.0 editor:newline (input.hidden-input)
     -1:07.4.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:07.4.0 editor:newline (input.hidden-input)
     -1:04.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:04.0 editor:newline (input.hidden-input)
     -0:58.7.0 core:delete (input.hidden-input)
     -0:55.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:55.8.0 editor:newline (input.hidden-input)
     -0:49.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:49.1.0 editor:newline (input.hidden-input)
  2x -0:40 core:copy (input.hidden-input)
     -0:32.8.0 core:paste (input.hidden-input)
     -0:27.4.0 core:save (input.hidden-input)
     -0:19.3.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:19.3.0 editor:newline (input.hidden-input)
     -0:18.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
markdown-assistant 0.2.0 
markdown-helper 0.3.0 
markdown-pdf 2.2.0 
markdown-preview-kramdown 0.6.1 
markdown-to-html 0.5.0 
markdown-writer 2.10.3 
pandoc 0.2.2 
```

**Comment by mselseth** [comment]
Same issue, ubuntu 18.10.
If I run atom with sudo, it creates the html file, but is protected.
By protected I mean Chromium cannot display it, it shows as protected.

-rw-r--r-- 1 root     root         734 Nov 17 15:09 test.html
